# Use Node.js LTS
FROM node:20

# Set working directory
WORKDIR /app

# Copy files
COPY package*.json ./
COPY index.js ./
COPY .env ./

# Install dependencies
RUN npm install

# Run the script
CMD ["node", "index.js"]
